-- 误解本资产初始化数据：写作表达 / 固定搭配 / 易混词
-- 共 300 条，每类 100 条

DELETE FROM `mistake_asset_library` WHERE `category` IN ('writing', 'phrase', 'confusion');

INSERT INTO `mistake_asset_library` (`category`, `subcategory`, `source_text`, `translation`, `source_hint`, `note`, `example_en`, `example_zh`, `source_module`, `sort_order`, `active`) VALUES
  ('writing','application_opening','I am writing to express my sincere gratitude for your help.','我写信是为了对您的帮助表达诚挚感谢。','application_opening 高频表达','适合考研英语写作直接复用。','I am writing to express my sincere gratitude for your help.','我写信是为了对您的帮助表达诚挚感谢。','系统资产库',1,1),
  ('writing','application_opening','I am writing to apply for the position advertised on your website.','我写信是想申请贵网站上发布的职位。','application_opening 高频表达','适合考研英语写作直接复用。','I am writing to apply for the position advertised on your website.','我写信是想申请贵网站上发布的职位。','系统资产库',2,1),
  ('writing','application_opening','I am writing to inquire about the details of the program.','我写信是想咨询该项目的具体信息。','application_opening 高频表达','适合考研英语写作直接复用。','I am writing to inquire about the details of the program.','我写信是想咨询该项目的具体信息。','系统资产库',3,1),
  ('writing','application_opening','I am writing to recommend a qualified candidate to you.','我写信是想向您推荐一位合格人选。','application_opening 高频表达','适合考研英语写作直接复用。','I am writing to recommend a qualified candidate to you.','我写信是想向您推荐一位合格人选。','系统资产库',4,1),
  ('writing','application_opening','I am writing to invite you to attend our upcoming activity.','我写信是想邀请您参加我们即将举行的活动。','application_opening 高频表达','适合考研英语写作直接复用。','I am writing to invite you to attend our upcoming activity.','我写信是想邀请您参加我们即将举行的活动。','系统资产库',5,1),
  ('writing','application_opening','I am writing to make a complaint about the service I received.','我写信是想投诉我所受到的服务。','application_opening 高频表达','适合考研英语写作直接复用。','I am writing to make a complaint about the service I received.','我写信是想投诉我所受到的服务。','系统资产库',6,1),
  ('writing','application_opening','I am writing to apologize for the inconvenience I have caused.','我写信是想为给您造成的不便道歉。','application_opening 高频表达','适合考研英语写作直接复用。','I am writing to apologize for the inconvenience I have caused.','我写信是想为给您造成的不便道歉。','系统资产库',7,1),
  ('writing','application_opening','I am writing to offer several suggestions on this issue.','我写信是想就这个问题提出几点建议。','application_opening 高频表达','适合考研英语写作直接复用。','I am writing to offer several suggestions on this issue.','我写信是想就这个问题提出几点建议。','系统资产库',8,1),
  ('writing','application_opening','I am delighted to learn that you have made great progress.','我很高兴得知您取得了很大进步。','application_opening 高频表达','适合考研英语写作直接复用。','I am delighted to learn that you have made great progress.','我很高兴得知您取得了很大进步。','系统资产库',9,1),
  ('writing','application_opening','Having learned that volunteers are needed, I am eager to join you.','得知需要志愿者后，我很想加入你们。','application_opening 高频表达','适合考研英语写作直接复用。','Having learned that volunteers are needed, I am eager to join you.','得知需要志愿者后，我很想加入你们。','系统资产库',10,1),
  ('writing','application_closing','Thank you very much for your time and consideration.','非常感谢您的时间和考虑。','application_closing 高频表达','适合考研英语写作直接复用。','Thank you very much for your time and consideration.','非常感谢您的时间和考虑。','系统资产库',11,1),
  ('writing','application_closing','I am looking forward to your favorable reply.','期待您的肯定回复。','application_closing 高频表达','适合考研英语写作直接复用。','I am looking forward to your favorable reply.','期待您的肯定回复。','系统资产库',12,1),
  ('writing','application_closing','I hope my suggestions will be of some help to you.','希望我的建议能对您有所帮助。','application_closing 高频表达','适合考研英语写作直接复用。','I hope my suggestions will be of some help to you.','希望我的建议能对您有所帮助。','系统资产库',13,1),
  ('writing','application_closing','Please accept my sincere appreciation once again.','请再次接受我诚挚的感谢。','application_closing 高频表达','适合考研英语写作直接复用。','Please accept my sincere appreciation once again.','请再次接受我诚挚的感谢。','系统资产库',14,1),
  ('writing','application_closing','I hope you can understand my situation and forgive me.','希望您能理解我的处境并原谅我。','application_closing 高频表达','适合考研英语写作直接复用。','I hope you can understand my situation and forgive me.','希望您能理解我的处境并原谅我。','系统资产库',15,1),
  ('writing','application_closing','Your prompt attention to this matter would be highly appreciated.','若您能尽快关注此事，我将十分感激。','application_closing 高频表达','适合考研英语写作直接复用。','Your prompt attention to this matter would be highly appreciated.','若您能尽快关注此事，我将十分感激。','系统资产库',16,1),
  ('writing','application_closing','I would appreciate an early reply at your convenience.','若您方便时尽早回复，我将不胜感激。','application_closing 高频表达','适合考研英语写作直接复用。','I would appreciate an early reply at your convenience.','若您方便时尽早回复，我将不胜感激。','系统资产库',17,1),
  ('writing','application_closing','Please let me know if further information is needed.','如果还需要更多信息，请告知。','application_closing 高频表达','适合考研英语写作直接复用。','Please let me know if further information is needed.','如果还需要更多信息，请告知。','系统资产库',18,1),
  ('writing','application_closing','I sincerely hope that my request will meet with your approval.','我真诚希望我的请求能够得到您的批准。','application_closing 高频表达','适合考研英语写作直接复用。','I sincerely hope that my request will meet with your approval.','我真诚希望我的请求能够得到您的批准。','系统资产库',19,1),
  ('writing','application_closing','Thank you again for your patience and support.','再次感谢您的耐心和支持。','application_closing 高频表达','适合考研英语写作直接复用。','Thank you again for your patience and support.','再次感谢您的耐心和支持。','系统资产库',20,1),
  ('writing','chart_intro','The chart clearly illustrates a noticeable change in people''s choices.','该图表清晰展示了人们选择上的明显变化。','chart_intro 高频表达','适合考研英语写作直接复用。','The chart clearly illustrates a noticeable change in people''s choices.','该图表清晰展示了人们选择上的明显变化。','系统资产库',21,1),
  ('writing','chart_intro','As is shown in the chart, the figure has changed significantly.','正如图表所示，该数字发生了显著变化。','chart_intro 高频表达','适合考研英语写作直接复用。','As is shown in the chart, the figure has changed significantly.','正如图表所示，该数字发生了显著变化。','系统资产库',22,1),
  ('writing','chart_intro','The table provides some interesting data regarding this trend.','该表格提供了关于这一趋势的一些有趣数据。','chart_intro 高频表达','适合考研英语写作直接复用。','The table provides some interesting data regarding this trend.','该表格提供了关于这一趋势的一些有趣数据。','系统资产库',23,1),
  ('writing','chart_intro','The figures in the chart reflect a clear social tendency.','图中的数据反映出一种清晰的社会趋势。','chart_intro 高频表达','适合考研英语写作直接复用。','The figures in the chart reflect a clear social tendency.','图中的数据反映出一种清晰的社会趋势。','系统资产库',24,1),
  ('writing','chart_intro','The diagram offers a vivid picture of a common social phenomenon.','该图形生动展示了一种常见社会现象。','chart_intro 高频表达','适合考研英语写作直接复用。','The diagram offers a vivid picture of a common social phenomenon.','该图形生动展示了一种常见社会现象。','系统资产库',25,1),
  ('writing','chart_intro','The statistics reveal significant changes in public behavior.','统计数据揭示了公众行为的显著变化。','chart_intro 高频表达','适合考研英语写作直接复用。','The statistics reveal significant changes in public behavior.','统计数据揭示了公众行为的显著变化。','系统资产库',26,1),
  ('writing','chart_intro','A careful look at the chart leads us to a useful conclusion.','仔细观察图表后，我们可以得出一个有用结论。','chart_intro 高频表达','适合考研英语写作直接复用。','A careful look at the chart leads us to a useful conclusion.','仔细观察图表后，我们可以得出一个有用结论。','系统资产库',27,1),
  ('writing','chart_intro','The bar chart compares different groups in terms of preference.','该柱状图从偏好方面比较了不同群体。','chart_intro 高频表达','适合考研英语写作直接复用。','The bar chart compares different groups in terms of preference.','该柱状图从偏好方面比较了不同群体。','系统资产库',28,1),
  ('writing','chart_intro','The pie chart shows how the total is distributed among categories.','该饼图展示了总量在不同类别中的分布。','chart_intro 高频表达','适合考研英语写作直接复用。','The pie chart shows how the total is distributed among categories.','该饼图展示了总量在不同类别中的分布。','系统资产库',29,1),
  ('writing','chart_intro','The line graph tracks the changes over time.','该折线图追踪了随时间发生的变化。','chart_intro 高频表达','适合考研英语写作直接复用。','The line graph tracks the changes over time.','该折线图追踪了随时间发生的变化。','系统资产库',30,1),
  ('writing','chart_trend','There has been a steady rise in the number of participants.','参与者数量一直在稳步上升。','chart_trend 高频表达','适合考研英语写作直接复用。','There has been a steady rise in the number of participants.','参与者数量一直在稳步上升。','系统资产库',31,1),
  ('writing','chart_trend','The percentage increased dramatically over the past decade.','该比例在过去十年大幅增长。','chart_trend 高频表达','适合考研英语写作直接复用。','The percentage increased dramatically over the past decade.','该比例在过去十年大幅增长。','系统资产库',32,1),
  ('writing','chart_trend','The figure almost doubled during the period.','这一数字在此期间几乎翻倍。','chart_trend 高频表达','适合考研英语写作直接复用。','The figure almost doubled during the period.','这一数字在此期间几乎翻倍。','系统资产库',33,1),
  ('writing','chart_trend','A significant upward trend can be observed in the chart.','图表中可以观察到明显上升趋势。','chart_trend 高频表达','适合考研英语写作直接复用。','A significant upward trend can be observed in the chart.','图表中可以观察到明显上升趋势。','系统资产库',34,1),
  ('writing','chart_trend','There has been a gradual decline in this percentage.','这一比例一直在逐渐下降。','chart_trend 高频表达','适合考研英语写作直接复用。','There has been a gradual decline in this percentage.','这一比例一直在逐渐下降。','系统资产库',35,1),
  ('writing','chart_trend','The figure dropped sharply within a short period.','该数字在短时间内急剧下降。','chart_trend 高频表达','适合考研英语写作直接复用。','The figure dropped sharply within a short period.','该数字在短时间内急剧下降。','系统资产库',36,1),
  ('writing','chart_trend','The proportion remained relatively stable.','该比例保持相对稳定。','chart_trend 高频表达','适合考研英语写作直接复用。','The proportion remained relatively stable.','该比例保持相对稳定。','系统资产库',37,1),
  ('writing','chart_trend','This change may be attributed to social development.','这种变化可能归因于社会发展。','chart_trend 高频表达','适合考研英语写作直接复用。','This change may be attributed to social development.','这种变化可能归因于社会发展。','系统资产库',38,1),
  ('writing','chart_trend','The upward tendency is likely to continue in the future.','这种上升趋势未来可能持续。','chart_trend 高频表达','适合考研英语写作直接复用。','The upward tendency is likely to continue in the future.','这种上升趋势未来可能持续。','系统资产库',39,1),
  ('writing','chart_trend','The data point to a shift in people''s priorities.','这些数据表明人们的优先事项发生了转变。','chart_trend 高频表达','适合考研英语写作直接复用。','The data point to a shift in people''s priorities.','这些数据表明人们的优先事项发生了转变。','系统资产库',40,1),
  ('writing','comparison','Compared with the former, the latter is more popular.','与前者相比，后者更受欢迎。','comparison 高频表达','适合考研英语写作直接复用。','Compared with the former, the latter is more popular.','与前者相比，后者更受欢迎。','系统资产库',41,1),
  ('writing','comparison','The difference between the two groups is quite striking.','两组之间的差异相当明显。','comparison 高频表达','适合考研英语写作直接复用。','The difference between the two groups is quite striking.','两组之间的差异相当明显。','系统资产库',42,1),
  ('writing','comparison','The former focuses on efficiency, whereas the latter values stability.','前者注重效率，而后者重视稳定。','comparison 高频表达','适合考研英语写作直接复用。','The former focuses on efficiency, whereas the latter values stability.','前者注重效率，而后者重视稳定。','系统资产库',43,1),
  ('writing','comparison','This gap suggests different priorities among different groups.','这种差距说明不同群体有不同的优先重点。','comparison 高频表达','适合考研英语写作直接复用。','This gap suggests different priorities among different groups.','这种差距说明不同群体有不同的优先重点。','系统资产库',44,1),
  ('writing','comparison','Similarly, both groups show a tendency to make practical choices.','类似地，两组都表现出做出务实选择的倾向。','comparison 高频表达','适合考研英语写作直接复用。','Similarly, both groups show a tendency to make practical choices.','类似地，两组都表现出做出务实选择的倾向。','系统资产库',45,1),
  ('writing','comparison','In contrast to traditional methods, this approach is more flexible.','与传统方法相比，这种方式更灵活。','comparison 高频表达','适合考研英语写作直接复用。','In contrast to traditional methods, this approach is more flexible.','与传统方法相比，这种方式更灵活。','系统资产库',46,1),
  ('writing','comparison','A far exceeds B in terms of convenience.','从便利性方面看，A远远超过B。','comparison 高频表达','适合考研英语写作直接复用。','A far exceeds B in terms of convenience.','从便利性方面看，A远远超过B。','系统资产库',47,1),
  ('writing','comparison','The contrast reveals a deeper change in mindset.','这种对比揭示了更深层的观念变化。','comparison 高频表达','适合考研英语写作直接复用。','The contrast reveals a deeper change in mindset.','这种对比揭示了更深层的观念变化。','系统资产库',48,1),
  ('writing','comparison','There is a clear gap between expectation and reality.','期待与现实之间存在明显差距。','comparison 高频表达','适合考研英语写作直接复用。','There is a clear gap between expectation and reality.','期待与现实之间存在明显差距。','系统资产库',49,1),
  ('writing','comparison','The two options differ greatly in cost and efficiency.','这两个选项在成本和效率上差异很大。','comparison 高频表达','适合考研英语写作直接复用。','The two options differ greatly in cost and efficiency.','这两个选项在成本和效率上差异很大。','系统资产库',50,1);

INSERT INTO `mistake_asset_library` (`category`, `subcategory`, `source_text`, `translation`, `source_hint`, `note`, `example_en`, `example_zh`, `source_module`, `sort_order`, `active`) VALUES
  ('writing','cause_effect','There are several factors responsible for this phenomenon.','造成这一现象的原因有好几个。','cause_effect 高频表达','适合考研英语写作直接复用。','There are several factors responsible for this phenomenon.','造成这一现象的原因有好几个。','系统资产库',51,1),
  ('writing','cause_effect','This phenomenon can be attributed to the following reasons.','这一现象可以归因于以下原因。','cause_effect 高频表达','适合考研英语写作直接复用。','This phenomenon can be attributed to the following reasons.','这一现象可以归因于以下原因。','系统资产库',52,1),
  ('writing','cause_effect','One major reason is that people have easier access to information.','一个主要原因是人们更容易获取信息。','cause_effect 高频表达','适合考研英语写作直接复用。','One major reason is that people have easier access to information.','一个主要原因是人们更容易获取信息。','系统资产库',53,1),
  ('writing','cause_effect','Another contributing factor lies in the rapid development of technology.','另一个促成因素在于技术的快速发展。','cause_effect 高频表达','适合考研英语写作直接复用。','Another contributing factor lies in the rapid development of technology.','另一个促成因素在于技术的快速发展。','系统资产库',54,1),
  ('writing','cause_effect','This trend will exert a profound influence on society.','这一趋势将对社会产生深远影响。','cause_effect 高频表达','适合考研英语写作直接复用。','This trend will exert a profound influence on society.','这一趋势将对社会产生深远影响。','系统资产库',55,1),
  ('writing','cause_effect','It not only affects individual choices, but also reshapes social values.','它不仅影响个人选择，还重塑社会价值观。','cause_effect 高频表达','适合考研英语写作直接复用。','It not only affects individual choices, but also reshapes social values.','它不仅影响个人选择，还重塑社会价值观。','系统资产库',56,1),
  ('writing','cause_effect','As a result, people are more likely to change their behavior.','因此，人们更有可能改变自己的行为。','cause_effect 高频表达','适合考研英语写作直接复用。','As a result, people are more likely to change their behavior.','因此，人们更有可能改变自己的行为。','系统资产库',57,1),
  ('writing','cause_effect','This, in turn, gives rise to new challenges.','这反过来又带来了新的挑战。','cause_effect 高频表达','适合考研英语写作直接复用。','This, in turn, gives rise to new challenges.','这反过来又带来了新的挑战。','系统资产库',58,1),
  ('writing','cause_effect','The problem stems partly from a lack of awareness.','这一问题部分源于意识不足。','cause_effect 高频表达','适合考研英语写作直接复用。','The problem stems partly from a lack of awareness.','这一问题部分源于意识不足。','系统资产库',59,1),
  ('writing','cause_effect','The change reflects both personal needs and social pressure.','这一变化既反映了个人需求，也反映了社会压力。','cause_effect 高频表达','适合考研英语写作直接复用。','The change reflects both personal needs and social pressure.','这一变化既反映了个人需求，也反映了社会压力。','系统资产库',60,1),
  ('writing','suggestion','It is advisable for us to take effective measures.','我们最好采取有效措施。','suggestion 高频表达','适合考研英语写作直接复用。','It is advisable for us to take effective measures.','我们最好采取有效措施。','系统资产库',61,1),
  ('writing','suggestion','More attention should be paid to this issue.','应当更多关注这一问题。','suggestion 高频表达','适合考研英语写作直接复用。','More attention should be paid to this issue.','应当更多关注这一问题。','系统资产库',62,1),
  ('writing','suggestion','Practical steps must be taken to improve the situation.','必须采取切实措施改善现状。','suggestion 高频表达','适合考研英语写作直接复用。','Practical steps must be taken to improve the situation.','必须采取切实措施改善现状。','系统资产库',63,1),
  ('writing','suggestion','It is high time that we placed greater emphasis on this matter.','现在确实该更加重视这一事项了。','suggestion 高频表达','适合考研英语写作直接复用。','It is high time that we placed greater emphasis on this matter.','现在确实该更加重视这一事项了。','系统资产库',64,1),
  ('writing','suggestion','Only in this way can we effectively solve the problem.','只有这样我们才能有效解决问题。','suggestion 高频表达','适合考研英语写作直接复用。','Only in this way can we effectively solve the problem.','只有这样我们才能有效解决问题。','系统资产库',65,1),
  ('writing','suggestion','The government and individuals should work together to address it.','政府和个人应共同努力解决这一问题。','suggestion 高频表达','适合考研英语写作直接复用。','The government and individuals should work together to address it.','政府和个人应共同努力解决这一问题。','系统资产库',66,1),
  ('writing','suggestion','A balanced approach is both necessary and realistic.','一种平衡的方法既必要又现实。','suggestion 高频表达','适合考研英语写作直接复用。','A balanced approach is both necessary and realistic.','一种平衡的方法既必要又现实。','系统资产库',67,1),
  ('writing','suggestion','We should make better use of available resources.','我们应更好地利用现有资源。','suggestion 高频表达','适合考研英语写作直接复用。','We should make better use of available resources.','我们应更好地利用现有资源。','系统资产库',68,1),
  ('writing','suggestion','Schools can play a more active role in this process.','学校可以在这一过程中发挥更积极的作用。','suggestion 高频表达','适合考研英语写作直接复用。','Schools can play a more active role in this process.','学校可以在这一过程中发挥更积极的作用。','系统资产库',69,1),
  ('writing','suggestion','Public awareness should be improved step by step.','公众意识应逐步提高。','suggestion 高频表达','适合考研英语写作直接复用。','Public awareness should be improved step by step.','公众意识应逐步提高。','系统资产库',70,1),
  ('writing','opinion','From my perspective, this issue deserves close attention.','在我看来，这一问题值得密切关注。','opinion 高频表达','适合考研英语写作直接复用。','From my perspective, this issue deserves close attention.','在我看来，这一问题值得密切关注。','系统资产库',71,1),
  ('writing','opinion','Personally, I strongly believe that self-discipline matters.','就我个人而言，我坚信自律很重要。','opinion 高频表达','适合考研英语写作直接复用。','Personally, I strongly believe that self-discipline matters.','就我个人而言，我坚信自律很重要。','系统资产库',72,1),
  ('writing','opinion','I am firmly convinced that lifelong learning is essential.','我坚信终身学习是必不可少的。','opinion 高频表达','适合考研英语写作直接复用。','I am firmly convinced that lifelong learning is essential.','我坚信终身学习是必不可少的。','系统资产库',73,1),
  ('writing','opinion','It is no exaggeration to say that technology has changed our life.','毫不夸张地说，技术改变了我们的生活。','opinion 高频表达','适合考研英语写作直接复用。','It is no exaggeration to say that technology has changed our life.','毫不夸张地说，技术改变了我们的生活。','系统资产库',74,1),
  ('writing','opinion','There is no denying that a healthy lifestyle matters.','不可否认的是，健康生活方式很重要。','opinion 高频表达','适合考研英语写作直接复用。','There is no denying that a healthy lifestyle matters.','不可否认的是，健康生活方式很重要。','系统资产库',75,1),
  ('writing','opinion','Few people can ignore the importance of responsibility.','很少有人能忽视责任的重要性。','opinion 高频表达','适合考研英语写作直接复用。','Few people can ignore the importance of responsibility.','很少有人能忽视责任的重要性。','系统资产库',76,1),
  ('writing','opinion','This issue should be viewed from a broader perspective.','这一问题应从更广阔的视角来看待。','opinion 高频表达','适合考研英语写作直接复用。','This issue should be viewed from a broader perspective.','这一问题应从更广阔的视角来看待。','系统资产库',77,1),
  ('writing','opinion','A rational attitude is badly needed in this debate.','这场讨论中迫切需要理性态度。','opinion 高频表达','适合考研英语写作直接复用。','A rational attitude is badly needed in this debate.','这场讨论中迫切需要理性态度。','系统资产库',78,1),
  ('writing','opinion','The value of this practice should not be underestimated.','这一做法的价值不应被低估。','opinion 高频表达','适合考研英语写作直接复用。','The value of this practice should not be underestimated.','这一做法的价值不应被低估。','系统资产库',79,1),
  ('writing','opinion','The key lies in finding a sustainable solution.','关键在于找到可持续的解决方案。','opinion 高频表达','适合考研英语写作直接复用。','The key lies in finding a sustainable solution.','关键在于找到可持续的解决方案。','系统资产库',80,1),
  ('writing','example_transition','A good case in point is the popularity of online learning.','一个很好的例子是在线学习的流行。','example_transition 高频表达','适合考研英语写作直接复用。','A good case in point is the popularity of online learning.','一个很好的例子是在线学习的流行。','系统资产库',81,1),
  ('writing','example_transition','Take mobile payment as an example.','以移动支付为例。','example_transition 高频表达','适合考研英语写作直接复用。','Take mobile payment as an example.','以移动支付为例。','系统资产库',82,1),
  ('writing','example_transition','This can be best illustrated by the rise of digital platforms.','这一点可以通过数字平台的兴起来最好地说明。','example_transition 高频表达','适合考研英语写作直接复用。','This can be best illustrated by the rise of digital platforms.','这一点可以通过数字平台的兴起来最好地说明。','系统资产库',83,1),
  ('writing','example_transition','Such examples can easily be found in our daily life.','这样的例子在日常生活中随处可见。','example_transition 高频表达','适合考研英语写作直接复用。','Such examples can easily be found in our daily life.','这样的例子在日常生活中随处可见。','系统资产库',84,1),
  ('writing','example_transition','To begin with, preparation is the key to success.','首先，准备是成功的关键。','example_transition 高频表达','适合考研英语写作直接复用。','To begin with, preparation is the key to success.','首先，准备是成功的关键。','系统资产库',85,1),
  ('writing','example_transition','What is more, this change benefits both sides.','而且，这一变化对双方都有好处。','example_transition 高频表达','适合考研英语写作直接复用。','What is more, this change benefits both sides.','而且，这一变化对双方都有好处。','系统资产库',86,1),
  ('writing','example_transition','More importantly, it helps people build confidence.','更重要的是，它帮助人们建立信心。','example_transition 高频表达','适合考研英语写作直接复用。','More importantly, it helps people build confidence.','更重要的是，它帮助人们建立信心。','系统资产库',87,1),
  ('writing','example_transition','In addition, public awareness should be improved.','此外，公众意识也应得到提升。','example_transition 高频表达','适合考研英语写作直接复用。','In addition, public awareness should be improved.','此外，公众意识也应得到提升。','系统资产库',88,1),
  ('writing','example_transition','By contrast, traditional methods are more stable.','相比之下，传统方法更稳定。','example_transition 高频表达','适合考研英语写作直接复用。','By contrast, traditional methods are more stable.','相比之下，传统方法更稳定。','系统资产库',89,1),
  ('writing','example_transition','Consequently, more people have started to rethink their priorities.','因此，更多人开始重新思考自己的优先事项。','example_transition 高频表达','适合考研英语写作直接复用。','Consequently, more people have started to rethink their priorities.','因此，更多人开始重新思考自己的优先事项。','系统资产库',90,1),
  ('writing','conclusion','In conclusion, it is essential to strike a balance.','总之，取得平衡至关重要。','conclusion 高频表达','适合考研英语写作直接复用。','In conclusion, it is essential to strike a balance.','总之，取得平衡至关重要。','系统资产库',91,1),
  ('writing','conclusion','To sum up, the benefits outweigh the drawbacks.','总的来说，好处大于弊端。','conclusion 高频表达','适合考研英语写作直接复用。','To sum up, the benefits outweigh the drawbacks.','总的来说，好处大于弊端。','系统资产库',92,1),
  ('writing','conclusion','All in all, this issue calls for continuous attention.','总而言之，这一问题需要持续关注。','conclusion 高频表达','适合考研英语写作直接复用。','All in all, this issue calls for continuous attention.','总而言之，这一问题需要持续关注。','系统资产库',93,1),
  ('writing','conclusion','Only by doing so can we embrace a better future.','只有这样我们才能迎来更好的未来。','conclusion 高频表达','适合考研英语写作直接复用。','Only by doing so can we embrace a better future.','只有这样我们才能迎来更好的未来。','系统资产库',94,1),
  ('writing','conclusion','It is reasonable to expect that the trend will continue.','有理由期待这一趋势将继续。','conclusion 高频表达','适合考研英语写作直接复用。','It is reasonable to expect that the trend will continue.','有理由期待这一趋势将继续。','系统资产库',95,1),
  ('writing','conclusion','The message conveyed by the picture is clear and thought-provoking.','这幅图传达的信息清晰而发人深省。','conclusion 高频表达','适合考研英语写作直接复用。','The message conveyed by the picture is clear and thought-provoking.','这幅图传达的信息清晰而发人深省。','系统资产库',96,1),
  ('writing','conclusion','What the chart suggests is not merely a change in numbers but a shift in mindset.','图表揭示的不只是数字变化，更是观念转变。','conclusion 高频表达','适合考研英语写作直接复用。','What the chart suggests is not merely a change in numbers but a shift in mindset.','图表揭示的不只是数字变化，更是观念转变。','系统资产库',97,1),
  ('writing','conclusion','Therefore, a balanced and forward-looking attitude is badly needed.','因此，我们迫切需要一种平衡且有前瞻性的态度。','conclusion 高频表达','适合考研英语写作直接复用。','Therefore, a balanced and forward-looking attitude is badly needed.','因此，我们迫切需要一种平衡且有前瞻性的态度。','系统资产库',98,1),
  ('writing','conclusion','In the long run, this change will prove meaningful.','从长远来看，这一变化将被证明是有意义的。','conclusion 高频表达','适合考研英语写作直接复用。','In the long run, this change will prove meaningful.','从长远来看，这一变化将被证明是有意义的。','系统资产库',99,1),
  ('writing','conclusion','The solution requires patience, cooperation and practical action.','解决方案需要耐心、合作和切实行动。','conclusion 高频表达','适合考研英语写作直接复用。','The solution requires patience, cooperation and practical action.','解决方案需要耐心、合作和切实行动。','系统资产库',100,1);

INSERT INTO `mistake_asset_library` (`category`, `subcategory`, `source_text`, `translation`, `source_hint`, `note`, `example_en`, `example_zh`, `source_module`, `sort_order`, `active`) VALUES
  ('phrase','reading','in terms of','就……而言','阅读里看到的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for reading practice.','这个固定搭配适合阅读里看到的场景。','系统资产库',1,1),
  ('phrase','translation','in terms of','就……而言','翻译里卡住的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for translation practice.','这个固定搭配适合翻译里卡住的场景。','系统资产库',2,1),
  ('phrase','cloze','in terms of','就……而言','完形里做错的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for cloze practice.','这个固定搭配适合完形里做错的场景。','系统资产库',3,1),
  ('phrase','writing','in terms of','就……而言','写作里可复用的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for writing practice.','这个固定搭配适合写作里可复用的场景。','系统资产库',4,1),
  ('phrase','reading','contribute to','促成；有助于；导致','阅读里看到的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for reading practice.','这个固定搭配适合阅读里看到的场景。','系统资产库',5,1),
  ('phrase','translation','contribute to','促成；有助于；导致','翻译里卡住的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for translation practice.','这个固定搭配适合翻译里卡住的场景。','系统资产库',6,1),
  ('phrase','cloze','contribute to','促成；有助于；导致','完形里做错的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for cloze practice.','这个固定搭配适合完形里做错的场景。','系统资产库',7,1),
  ('phrase','writing','contribute to','促成；有助于；导致','写作里可复用的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for writing practice.','这个固定搭配适合写作里可复用的场景。','系统资产库',8,1),
  ('phrase','reading','be associated with','与……相关联','阅读里看到的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for reading practice.','这个固定搭配适合阅读里看到的场景。','系统资产库',9,1),
  ('phrase','translation','be associated with','与……相关联','翻译里卡住的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for translation practice.','这个固定搭配适合翻译里卡住的场景。','系统资产库',10,1),
  ('phrase','cloze','be associated with','与……相关联','完形里做错的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for cloze practice.','这个固定搭配适合完形里做错的场景。','系统资产库',11,1),
  ('phrase','writing','be associated with','与……相关联','写作里可复用的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for writing practice.','这个固定搭配适合写作里可复用的场景。','系统资产库',12,1),
  ('phrase','reading','take responsibility for','对……负责','阅读里看到的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for reading practice.','这个固定搭配适合阅读里看到的场景。','系统资产库',13,1),
  ('phrase','translation','take responsibility for','对……负责','翻译里卡住的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for translation practice.','这个固定搭配适合翻译里卡住的场景。','系统资产库',14,1),
  ('phrase','cloze','take responsibility for','对……负责','完形里做错的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for cloze practice.','这个固定搭配适合完形里做错的场景。','系统资产库',15,1),
  ('phrase','writing','take responsibility for','对……负责','写作里可复用的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for writing practice.','这个固定搭配适合写作里可复用的场景。','系统资产库',16,1),
  ('phrase','reading','play a role in','在……中发挥作用','阅读里看到的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for reading practice.','这个固定搭配适合阅读里看到的场景。','系统资产库',17,1),
  ('phrase','translation','play a role in','在……中发挥作用','翻译里卡住的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for translation practice.','这个固定搭配适合翻译里卡住的场景。','系统资产库',18,1),
  ('phrase','cloze','play a role in','在……中发挥作用','完形里做错的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for cloze practice.','这个固定搭配适合完形里做错的场景。','系统资产库',19,1),
  ('phrase','writing','play a role in','在……中发挥作用','写作里可复用的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for writing practice.','这个固定搭配适合写作里可复用的场景。','系统资产库',20,1),
  ('phrase','reading','lead to','导致','阅读里看到的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for reading practice.','这个固定搭配适合阅读里看到的场景。','系统资产库',21,1),
  ('phrase','translation','lead to','导致','翻译里卡住的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for translation practice.','这个固定搭配适合翻译里卡住的场景。','系统资产库',22,1),
  ('phrase','cloze','lead to','导致','完形里做错的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for cloze practice.','这个固定搭配适合完形里做错的场景。','系统资产库',23,1),
  ('phrase','writing','lead to','导致','写作里可复用的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for writing practice.','这个固定搭配适合写作里可复用的场景。','系统资产库',24,1),
  ('phrase','reading','result in','导致','阅读里看到的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for reading practice.','这个固定搭配适合阅读里看到的场景。','系统资产库',25,1),
  ('phrase','translation','result in','导致','翻译里卡住的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for translation practice.','这个固定搭配适合翻译里卡住的场景。','系统资产库',26,1),
  ('phrase','cloze','result in','导致','完形里做错的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for cloze practice.','这个固定搭配适合完形里做错的场景。','系统资产库',27,1),
  ('phrase','writing','result in','导致','写作里可复用的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for writing practice.','这个固定搭配适合写作里可复用的场景。','系统资产库',28,1),
  ('phrase','reading','result from','源于','阅读里看到的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for reading practice.','这个固定搭配适合阅读里看到的场景。','系统资产库',29,1),
  ('phrase','translation','result from','源于','翻译里卡住的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for translation practice.','这个固定搭配适合翻译里卡住的场景。','系统资产库',30,1),
  ('phrase','cloze','result from','源于','完形里做错的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for cloze practice.','这个固定搭配适合完形里做错的场景。','系统资产库',31,1),
  ('phrase','writing','result from','源于','写作里可复用的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for writing practice.','这个固定搭配适合写作里可复用的场景。','系统资产库',32,1),
  ('phrase','reading','give rise to','引起；导致','阅读里看到的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for reading practice.','这个固定搭配适合阅读里看到的场景。','系统资产库',33,1),
  ('phrase','translation','give rise to','引起；导致','翻译里卡住的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for translation practice.','这个固定搭配适合翻译里卡住的场景。','系统资产库',34,1),
  ('phrase','cloze','give rise to','引起；导致','完形里做错的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for cloze practice.','这个固定搭配适合完形里做错的场景。','系统资产库',35,1),
  ('phrase','writing','give rise to','引起；导致','写作里可复用的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for writing practice.','这个固定搭配适合写作里可复用的场景。','系统资产库',36,1),
  ('phrase','reading','account for','占据；解释','阅读里看到的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for reading practice.','这个固定搭配适合阅读里看到的场景。','系统资产库',37,1),
  ('phrase','translation','account for','占据；解释','翻译里卡住的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for translation practice.','这个固定搭配适合翻译里卡住的场景。','系统资产库',38,1),
  ('phrase','cloze','account for','占据；解释','完形里做错的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for cloze practice.','这个固定搭配适合完形里做错的场景。','系统资产库',39,1),
  ('phrase','writing','account for','占据；解释','写作里可复用的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for writing practice.','这个固定搭配适合写作里可复用的场景。','系统资产库',40,1),
  ('phrase','reading','be likely to','有可能','阅读里看到的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for reading practice.','这个固定搭配适合阅读里看到的场景。','系统资产库',41,1),
  ('phrase','translation','be likely to','有可能','翻译里卡住的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for translation practice.','这个固定搭配适合翻译里卡住的场景。','系统资产库',42,1),
  ('phrase','cloze','be likely to','有可能','完形里做错的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for cloze practice.','这个固定搭配适合完形里做错的场景。','系统资产库',43,1),
  ('phrase','writing','be likely to','有可能','写作里可复用的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for writing practice.','这个固定搭配适合写作里可复用的场景。','系统资产库',44,1),
  ('phrase','reading','be exposed to','接触到；暴露于','阅读里看到的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for reading practice.','这个固定搭配适合阅读里看到的场景。','系统资产库',45,1),
  ('phrase','translation','be exposed to','接触到；暴露于','翻译里卡住的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for translation practice.','这个固定搭配适合翻译里卡住的场景。','系统资产库',46,1),
  ('phrase','cloze','be exposed to','接触到；暴露于','完形里做错的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for cloze practice.','这个固定搭配适合完形里做错的场景。','系统资产库',47,1),
  ('phrase','writing','be exposed to','接触到；暴露于','写作里可复用的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for writing practice.','这个固定搭配适合写作里可复用的场景。','系统资产库',48,1),
  ('phrase','reading','be based on','以……为基础','阅读里看到的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for reading practice.','这个固定搭配适合阅读里看到的场景。','系统资产库',49,1),
  ('phrase','translation','be based on','以……为基础','翻译里卡住的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for translation practice.','这个固定搭配适合翻译里卡住的场景。','系统资产库',50,1);

INSERT INTO `mistake_asset_library` (`category`, `subcategory`, `source_text`, `translation`, `source_hint`, `note`, `example_en`, `example_zh`, `source_module`, `sort_order`, `active`) VALUES
  ('phrase','cloze','be based on','以……为基础','完形里做错的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for cloze practice.','这个固定搭配适合完形里做错的场景。','系统资产库',51,1),
  ('phrase','writing','be based on','以……为基础','写作里可复用的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for writing practice.','这个固定搭配适合写作里可复用的场景。','系统资产库',52,1),
  ('phrase','reading','take into account','考虑到','阅读里看到的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for reading practice.','这个固定搭配适合阅读里看到的场景。','系统资产库',53,1),
  ('phrase','translation','take into account','考虑到','翻译里卡住的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for translation practice.','这个固定搭配适合翻译里卡住的场景。','系统资产库',54,1),
  ('phrase','cloze','take into account','考虑到','完形里做错的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for cloze practice.','这个固定搭配适合完形里做错的场景。','系统资产库',55,1),
  ('phrase','writing','take into account','考虑到','写作里可复用的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for writing practice.','这个固定搭配适合写作里可复用的场景。','系统资产库',56,1),
  ('phrase','reading','take advantage of','利用','阅读里看到的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for reading practice.','这个固定搭配适合阅读里看到的场景。','系统资产库',57,1),
  ('phrase','translation','take advantage of','利用','翻译里卡住的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for translation practice.','这个固定搭配适合翻译里卡住的场景。','系统资产库',58,1),
  ('phrase','cloze','take advantage of','利用','完形里做错的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for cloze practice.','这个固定搭配适合完形里做错的场景。','系统资产库',59,1),
  ('phrase','writing','take advantage of','利用','写作里可复用的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for writing practice.','这个固定搭配适合写作里可复用的场景。','系统资产库',60,1),
  ('phrase','reading','make use of','利用','阅读里看到的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for reading practice.','这个固定搭配适合阅读里看到的场景。','系统资产库',61,1),
  ('phrase','translation','make use of','利用','翻译里卡住的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for translation practice.','这个固定搭配适合翻译里卡住的场景。','系统资产库',62,1),
  ('phrase','cloze','make use of','利用','完形里做错的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for cloze practice.','这个固定搭配适合完形里做错的场景。','系统资产库',63,1),
  ('phrase','writing','make use of','利用','写作里可复用的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for writing practice.','这个固定搭配适合写作里可复用的场景。','系统资产库',64,1),
  ('phrase','reading','put emphasis on','强调','阅读里看到的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for reading practice.','这个固定搭配适合阅读里看到的场景。','系统资产库',65,1),
  ('phrase','translation','put emphasis on','强调','翻译里卡住的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for translation practice.','这个固定搭配适合翻译里卡住的场景。','系统资产库',66,1),
  ('phrase','cloze','put emphasis on','强调','完形里做错的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for cloze practice.','这个固定搭配适合完形里做错的场景。','系统资产库',67,1),
  ('phrase','writing','put emphasis on','强调','写作里可复用的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for writing practice.','这个固定搭配适合写作里可复用的场景。','系统资产库',68,1),
  ('phrase','reading','benefit from','从……中受益','阅读里看到的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for reading practice.','这个固定搭配适合阅读里看到的场景。','系统资产库',69,1),
  ('phrase','translation','benefit from','从……中受益','翻译里卡住的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for translation practice.','这个固定搭配适合翻译里卡住的场景。','系统资产库',70,1),
  ('phrase','cloze','benefit from','从……中受益','完形里做错的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for cloze practice.','这个固定搭配适合完形里做错的场景。','系统资产库',71,1),
  ('phrase','writing','benefit from','从……中受益','写作里可复用的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for writing practice.','这个固定搭配适合写作里可复用的场景。','系统资产库',72,1),
  ('phrase','reading','suffer from','遭受','阅读里看到的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for reading practice.','这个固定搭配适合阅读里看到的场景。','系统资产库',73,1),
  ('phrase','translation','suffer from','遭受','翻译里卡住的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for translation practice.','这个固定搭配适合翻译里卡住的场景。','系统资产库',74,1),
  ('phrase','cloze','suffer from','遭受','完形里做错的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for cloze practice.','这个固定搭配适合完形里做错的场景。','系统资产库',75,1),
  ('phrase','writing','suffer from','遭受','写作里可复用的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for writing practice.','这个固定搭配适合写作里可复用的场景。','系统资产库',76,1),
  ('phrase','reading','cope with','应对','阅读里看到的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for reading practice.','这个固定搭配适合阅读里看到的场景。','系统资产库',77,1),
  ('phrase','translation','cope with','应对','翻译里卡住的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for translation practice.','这个固定搭配适合翻译里卡住的场景。','系统资产库',78,1),
  ('phrase','cloze','cope with','应对','完形里做错的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for cloze practice.','这个固定搭配适合完形里做错的场景。','系统资产库',79,1),
  ('phrase','writing','cope with','应对','写作里可复用的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for writing practice.','这个固定搭配适合写作里可复用的场景。','系统资产库',80,1),
  ('phrase','reading','depend on','依赖；取决于','阅读里看到的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for reading practice.','这个固定搭配适合阅读里看到的场景。','系统资产库',81,1),
  ('phrase','translation','depend on','依赖；取决于','翻译里卡住的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for translation practice.','这个固定搭配适合翻译里卡住的场景。','系统资产库',82,1),
  ('phrase','cloze','depend on','依赖；取决于','完形里做错的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for cloze practice.','这个固定搭配适合完形里做错的场景。','系统资产库',83,1),
  ('phrase','writing','depend on','依赖；取决于','写作里可复用的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for writing practice.','这个固定搭配适合写作里可复用的场景。','系统资产库',84,1),
  ('phrase','reading','stem from','源于','阅读里看到的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for reading practice.','这个固定搭配适合阅读里看到的场景。','系统资产库',85,1),
  ('phrase','translation','stem from','源于','翻译里卡住的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for translation practice.','这个固定搭配适合翻译里卡住的场景。','系统资产库',86,1),
  ('phrase','cloze','stem from','源于','完形里做错的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for cloze practice.','这个固定搭配适合完形里做错的场景。','系统资产库',87,1),
  ('phrase','writing','stem from','源于','写作里可复用的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for writing practice.','这个固定搭配适合写作里可复用的场景。','系统资产库',88,1),
  ('phrase','reading','have access to','有机会接触/使用','阅读里看到的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for reading practice.','这个固定搭配适合阅读里看到的场景。','系统资产库',89,1),
  ('phrase','translation','have access to','有机会接触/使用','翻译里卡住的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for translation practice.','这个固定搭配适合翻译里卡住的场景。','系统资产库',90,1),
  ('phrase','cloze','have access to','有机会接触/使用','完形里做错的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for cloze practice.','这个固定搭配适合完形里做错的场景。','系统资产库',91,1),
  ('phrase','writing','have access to','有机会接触/使用','写作里可复用的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for writing practice.','这个固定搭配适合写作里可复用的场景。','系统资产库',92,1),
  ('phrase','reading','attach importance to','重视','阅读里看到的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for reading practice.','这个固定搭配适合阅读里看到的场景。','系统资产库',93,1),
  ('phrase','translation','attach importance to','重视','翻译里卡住的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for translation practice.','这个固定搭配适合翻译里卡住的场景。','系统资产库',94,1),
  ('phrase','cloze','attach importance to','重视','完形里做错的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for cloze practice.','这个固定搭配适合完形里做错的场景。','系统资产库',95,1),
  ('phrase','writing','attach importance to','重视','写作里可复用的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for writing practice.','这个固定搭配适合写作里可复用的场景。','系统资产库',96,1),
  ('phrase','reading','have an impact on','对……有影响','阅读里看到的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for reading practice.','这个固定搭配适合阅读里看到的场景。','系统资产库',97,1),
  ('phrase','translation','have an impact on','对……有影响','翻译里卡住的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for translation practice.','这个固定搭配适合翻译里卡住的场景。','系统资产库',98,1),
  ('phrase','cloze','have an impact on','对……有影响','完形里做错的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for cloze practice.','这个固定搭配适合完形里做错的场景。','系统资产库',99,1),
  ('phrase','writing','have an impact on','对……有影响','写作里可复用的','比单词更接近真实考试表达，应优先复盘。','This phrase is useful for writing practice.','这个固定搭配适合写作里可复用的场景。','系统资产库',100,1);

INSERT INTO `mistake_asset_library` (`category`, `subcategory`, `source_text`, `translation`, `source_hint`, `note`, `example_en`, `example_zh`, `source_module`, `sort_order`, `active`) VALUES
  ('confusion','reading','economic / economical','economic: 经济的；economical: 节俭的 / 省钱的','阅读辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: economic / economical.','注意这组词的区别：economic / economical。','系统资产库',1,1),
  ('confusion','writing','economic / economical','economic: 经济的；economical: 节俭的 / 省钱的','写作避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: economic / economical.','注意这组词的区别：economic / economical。','系统资产库',2,1),
  ('confusion','translation','economic / economical','economic: 经济的；economical: 节俭的 / 省钱的','翻译避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: economic / economical.','注意这组词的区别：economic / economical。','系统资产库',3,1),
  ('confusion','cloze','economic / economical','economic: 经济的；economical: 节俭的 / 省钱的','完形辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: economic / economical.','注意这组词的区别：economic / economical。','系统资产库',4,1),
  ('confusion','daily','economic / economical','economic: 经济的；economical: 节俭的 / 省钱的','基础高频','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: economic / economical.','注意这组词的区别：economic / economical。','系统资产库',5,1),
  ('confusion','reading','adapt / adopt','adapt: 适应 / 改编；adopt: 采纳 / 收养','阅读辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: adapt / adopt.','注意这组词的区别：adapt / adopt。','系统资产库',6,1),
  ('confusion','writing','adapt / adopt','adapt: 适应 / 改编；adopt: 采纳 / 收养','写作避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: adapt / adopt.','注意这组词的区别：adapt / adopt。','系统资产库',7,1),
  ('confusion','translation','adapt / adopt','adapt: 适应 / 改编；adopt: 采纳 / 收养','翻译避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: adapt / adopt.','注意这组词的区别：adapt / adopt。','系统资产库',8,1),
  ('confusion','cloze','adapt / adopt','adapt: 适应 / 改编；adopt: 采纳 / 收养','完形辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: adapt / adopt.','注意这组词的区别：adapt / adopt。','系统资产库',9,1),
  ('confusion','daily','adapt / adopt','adapt: 适应 / 改编；adopt: 采纳 / 收养','基础高频','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: adapt / adopt.','注意这组词的区别：adapt / adopt。','系统资产库',10,1),
  ('confusion','reading','affect / effect','affect 多作动词；effect 多作名词','阅读辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: affect / effect.','注意这组词的区别：affect / effect。','系统资产库',11,1),
  ('confusion','writing','affect / effect','affect 多作动词；effect 多作名词','写作避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: affect / effect.','注意这组词的区别：affect / effect。','系统资产库',12,1),
  ('confusion','translation','affect / effect','affect 多作动词；effect 多作名词','翻译避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: affect / effect.','注意这组词的区别：affect / effect。','系统资产库',13,1),
  ('confusion','cloze','affect / effect','affect 多作动词；effect 多作名词','完形辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: affect / effect.','注意这组词的区别：affect / effect。','系统资产库',14,1),
  ('confusion','daily','affect / effect','affect 多作动词；effect 多作名词','基础高频','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: affect / effect.','注意这组词的区别：affect / effect。','系统资产库',15,1),
  ('confusion','reading','accept / except','accept: 接受；except: 除……之外','阅读辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: accept / except.','注意这组词的区别：accept / except。','系统资产库',16,1),
  ('confusion','writing','accept / except','accept: 接受；except: 除……之外','写作避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: accept / except.','注意这组词的区别：accept / except。','系统资产库',17,1),
  ('confusion','translation','accept / except','accept: 接受；except: 除……之外','翻译避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: accept / except.','注意这组词的区别：accept / except。','系统资产库',18,1),
  ('confusion','cloze','accept / except','accept: 接受；except: 除……之外','完形辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: accept / except.','注意这组词的区别：accept / except。','系统资产库',19,1),
  ('confusion','daily','accept / except','accept: 接受；except: 除……之外','基础高频','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: accept / except.','注意这组词的区别：accept / except。','系统资产库',20,1),
  ('confusion','reading','beside / besides','beside: 在旁边；besides: 此外','阅读辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: beside / besides.','注意这组词的区别：beside / besides。','系统资产库',21,1),
  ('confusion','writing','beside / besides','beside: 在旁边；besides: 此外','写作避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: beside / besides.','注意这组词的区别：beside / besides。','系统资产库',22,1),
  ('confusion','translation','beside / besides','beside: 在旁边；besides: 此外','翻译避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: beside / besides.','注意这组词的区别：beside / besides。','系统资产库',23,1),
  ('confusion','cloze','beside / besides','beside: 在旁边；besides: 此外','完形辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: beside / besides.','注意这组词的区别：beside / besides。','系统资产库',24,1),
  ('confusion','daily','beside / besides','beside: 在旁边；besides: 此外','基础高频','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: beside / besides.','注意这组词的区别：beside / besides。','系统资产库',25,1),
  ('confusion','reading','personal / personnel','personal: 个人的；personnel: 人员','阅读辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: personal / personnel.','注意这组词的区别：personal / personnel。','系统资产库',26,1),
  ('confusion','writing','personal / personnel','personal: 个人的；personnel: 人员','写作避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: personal / personnel.','注意这组词的区别：personal / personnel。','系统资产库',27,1),
  ('confusion','translation','personal / personnel','personal: 个人的；personnel: 人员','翻译避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: personal / personnel.','注意这组词的区别：personal / personnel。','系统资产库',28,1),
  ('confusion','cloze','personal / personnel','personal: 个人的；personnel: 人员','完形辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: personal / personnel.','注意这组词的区别：personal / personnel。','系统资产库',29,1),
  ('confusion','daily','personal / personnel','personal: 个人的；personnel: 人员','基础高频','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: personal / personnel.','注意这组词的区别：personal / personnel。','系统资产库',30,1),
  ('confusion','reading','principal / principle','principal: 负责人/主要的；principle: 原则','阅读辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: principal / principle.','注意这组词的区别：principal / principle。','系统资产库',31,1),
  ('confusion','writing','principal / principle','principal: 负责人/主要的；principle: 原则','写作避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: principal / principle.','注意这组词的区别：principal / principle。','系统资产库',32,1),
  ('confusion','translation','principal / principle','principal: 负责人/主要的；principle: 原则','翻译避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: principal / principle.','注意这组词的区别：principal / principle。','系统资产库',33,1),
  ('confusion','cloze','principal / principle','principal: 负责人/主要的；principle: 原则','完形辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: principal / principle.','注意这组词的区别：principal / principle。','系统资产库',34,1),
  ('confusion','daily','principal / principle','principal: 负责人/主要的；principle: 原则','基础高频','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: principal / principle.','注意这组词的区别：principal / principle。','系统资产库',35,1),
  ('confusion','reading','compliment / complement','compliment: 赞美；complement: 补充','阅读辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: compliment / complement.','注意这组词的区别：compliment / complement。','系统资产库',36,1),
  ('confusion','writing','compliment / complement','compliment: 赞美；complement: 补充','写作避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: compliment / complement.','注意这组词的区别：compliment / complement。','系统资产库',37,1),
  ('confusion','translation','compliment / complement','compliment: 赞美；complement: 补充','翻译避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: compliment / complement.','注意这组词的区别：compliment / complement。','系统资产库',38,1),
  ('confusion','cloze','compliment / complement','compliment: 赞美；complement: 补充','完形辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: compliment / complement.','注意这组词的区别：compliment / complement。','系统资产库',39,1),
  ('confusion','daily','compliment / complement','compliment: 赞美；complement: 补充','基础高频','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: compliment / complement.','注意这组词的区别：compliment / complement。','系统资产库',40,1),
  ('confusion','reading','stationary / stationery','stationary: 静止的；stationery: 文具','阅读辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: stationary / stationery.','注意这组词的区别：stationary / stationery。','系统资产库',41,1),
  ('confusion','writing','stationary / stationery','stationary: 静止的；stationery: 文具','写作避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: stationary / stationery.','注意这组词的区别：stationary / stationery。','系统资产库',42,1),
  ('confusion','translation','stationary / stationery','stationary: 静止的；stationery: 文具','翻译避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: stationary / stationery.','注意这组词的区别：stationary / stationery。','系统资产库',43,1),
  ('confusion','cloze','stationary / stationery','stationary: 静止的；stationery: 文具','完形辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: stationary / stationery.','注意这组词的区别：stationary / stationery。','系统资产库',44,1),
  ('confusion','daily','stationary / stationery','stationary: 静止的；stationery: 文具','基础高频','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: stationary / stationery.','注意这组词的区别：stationary / stationery。','系统资产库',45,1),
  ('confusion','reading','later / latter','later: 后来；latter: 后者','阅读辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: later / latter.','注意这组词的区别：later / latter。','系统资产库',46,1),
  ('confusion','writing','later / latter','later: 后来；latter: 后者','写作避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: later / latter.','注意这组词的区别：later / latter。','系统资产库',47,1),
  ('confusion','translation','later / latter','later: 后来；latter: 后者','翻译避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: later / latter.','注意这组词的区别：later / latter。','系统资产库',48,1),
  ('confusion','cloze','later / latter','later: 后来；latter: 后者','完形辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: later / latter.','注意这组词的区别：later / latter。','系统资产库',49,1),
  ('confusion','daily','later / latter','later: 后来；latter: 后者','基础高频','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: later / latter.','注意这组词的区别：later / latter。','系统资产库',50,1);

INSERT INTO `mistake_asset_library` (`category`, `subcategory`, `source_text`, `translation`, `source_hint`, `note`, `example_en`, `example_zh`, `source_module`, `sort_order`, `active`) VALUES
  ('confusion','reading','rise / raise','rise: 上升；raise: 提高','阅读辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: rise / raise.','注意这组词的区别：rise / raise。','系统资产库',51,1),
  ('confusion','writing','rise / raise','rise: 上升；raise: 提高','写作避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: rise / raise.','注意这组词的区别：rise / raise。','系统资产库',52,1),
  ('confusion','translation','rise / raise','rise: 上升；raise: 提高','翻译避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: rise / raise.','注意这组词的区别：rise / raise。','系统资产库',53,1),
  ('confusion','cloze','rise / raise','rise: 上升；raise: 提高','完形辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: rise / raise.','注意这组词的区别：rise / raise。','系统资产库',54,1),
  ('confusion','daily','rise / raise','rise: 上升；raise: 提高','基础高频','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: rise / raise.','注意这组词的区别：rise / raise。','系统资产库',55,1),
  ('confusion','reading','lay / lie','lay: 放置；lie: 躺','阅读辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: lay / lie.','注意这组词的区别：lay / lie。','系统资产库',56,1),
  ('confusion','writing','lay / lie','lay: 放置；lie: 躺','写作避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: lay / lie.','注意这组词的区别：lay / lie。','系统资产库',57,1),
  ('confusion','translation','lay / lie','lay: 放置；lie: 躺','翻译避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: lay / lie.','注意这组词的区别：lay / lie。','系统资产库',58,1),
  ('confusion','cloze','lay / lie','lay: 放置；lie: 躺','完形辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: lay / lie.','注意这组词的区别：lay / lie。','系统资产库',59,1),
  ('confusion','daily','lay / lie','lay: 放置；lie: 躺','基础高频','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: lay / lie.','注意这组词的区别：lay / lie。','系统资产库',60,1),
  ('confusion','reading','borrow / lend','borrow: 借入；lend: 借出','阅读辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: borrow / lend.','注意这组词的区别：borrow / lend。','系统资产库',61,1),
  ('confusion','writing','borrow / lend','borrow: 借入；lend: 借出','写作避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: borrow / lend.','注意这组词的区别：borrow / lend。','系统资产库',62,1),
  ('confusion','translation','borrow / lend','borrow: 借入；lend: 借出','翻译避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: borrow / lend.','注意这组词的区别：borrow / lend。','系统资产库',63,1),
  ('confusion','cloze','borrow / lend','borrow: 借入；lend: 借出','完形辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: borrow / lend.','注意这组词的区别：borrow / lend。','系统资产库',64,1),
  ('confusion','daily','borrow / lend','borrow: 借入；lend: 借出','基础高频','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: borrow / lend.','注意这组词的区别：borrow / lend。','系统资产库',65,1),
  ('confusion','reading','say / tell','say: 说；tell: 告诉','阅读辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: say / tell.','注意这组词的区别：say / tell。','系统资产库',66,1),
  ('confusion','writing','say / tell','say: 说；tell: 告诉','写作避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: say / tell.','注意这组词的区别：say / tell。','系统资产库',67,1),
  ('confusion','translation','say / tell','say: 说；tell: 告诉','翻译避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: say / tell.','注意这组词的区别：say / tell。','系统资产库',68,1),
  ('confusion','cloze','say / tell','say: 说；tell: 告诉','完形辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: say / tell.','注意这组词的区别：say / tell。','系统资产库',69,1),
  ('confusion','daily','say / tell','say: 说；tell: 告诉','基础高频','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: say / tell.','注意这组词的区别：say / tell。','系统资产库',70,1),
  ('confusion','reading','speak / talk','speak: 讲语言/发言；talk: 交谈','阅读辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: speak / talk.','注意这组词的区别：speak / talk。','系统资产库',71,1),
  ('confusion','writing','speak / talk','speak: 讲语言/发言；talk: 交谈','写作避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: speak / talk.','注意这组词的区别：speak / talk。','系统资产库',72,1),
  ('confusion','translation','speak / talk','speak: 讲语言/发言；talk: 交谈','翻译避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: speak / talk.','注意这组词的区别：speak / talk。','系统资产库',73,1),
  ('confusion','cloze','speak / talk','speak: 讲语言/发言；talk: 交谈','完形辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: speak / talk.','注意这组词的区别：speak / talk。','系统资产库',74,1),
  ('confusion','daily','speak / talk','speak: 讲语言/发言；talk: 交谈','基础高频','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: speak / talk.','注意这组词的区别：speak / talk。','系统资产库',75,1),
  ('confusion','reading','job / work','job: 一份工作；work: 工作','阅读辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: job / work.','注意这组词的区别：job / work。','系统资产库',76,1),
  ('confusion','writing','job / work','job: 一份工作；work: 工作','写作避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: job / work.','注意这组词的区别：job / work。','系统资产库',77,1),
  ('confusion','translation','job / work','job: 一份工作；work: 工作','翻译避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: job / work.','注意这组词的区别：job / work。','系统资产库',78,1),
  ('confusion','cloze','job / work','job: 一份工作；work: 工作','完形辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: job / work.','注意这组词的区别：job / work。','系统资产库',79,1),
  ('confusion','daily','job / work','job: 一份工作；work: 工作','基础高频','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: job / work.','注意这组词的区别：job / work。','系统资产库',80,1),
  ('confusion','reading','advice / advise','advice: 建议；advise: 建议','阅读辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: advice / advise.','注意这组词的区别：advice / advise。','系统资产库',81,1),
  ('confusion','writing','advice / advise','advice: 建议；advise: 建议','写作避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: advice / advise.','注意这组词的区别：advice / advise。','系统资产库',82,1),
  ('confusion','translation','advice / advise','advice: 建议；advise: 建议','翻译避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: advice / advise.','注意这组词的区别：advice / advise。','系统资产库',83,1),
  ('confusion','cloze','advice / advise','advice: 建议；advise: 建议','完形辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: advice / advise.','注意这组词的区别：advice / advise。','系统资产库',84,1),
  ('confusion','daily','advice / advise','advice: 建议；advise: 建议','基础高频','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: advice / advise.','注意这组词的区别：advice / advise。','系统资产库',85,1),
  ('confusion','reading','success / succeed','success: 成功；succeed: 成功','阅读辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: success / succeed.','注意这组词的区别：success / succeed。','系统资产库',86,1),
  ('confusion','writing','success / succeed','success: 成功；succeed: 成功','写作避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: success / succeed.','注意这组词的区别：success / succeed。','系统资产库',87,1),
  ('confusion','translation','success / succeed','success: 成功；succeed: 成功','翻译避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: success / succeed.','注意这组词的区别：success / succeed。','系统资产库',88,1),
  ('confusion','cloze','success / succeed','success: 成功；succeed: 成功','完形辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: success / succeed.','注意这组词的区别：success / succeed。','系统资产库',89,1),
  ('confusion','daily','success / succeed','success: 成功；succeed: 成功','基础高频','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: success / succeed.','注意这组词的区别：success / succeed。','系统资产库',90,1),
  ('confusion','reading','valuable / priceless','valuable: 有价值；priceless: 无价','阅读辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: valuable / priceless.','注意这组词的区别：valuable / priceless。','系统资产库',91,1),
  ('confusion','writing','valuable / priceless','valuable: 有价值；priceless: 无价','写作避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: valuable / priceless.','注意这组词的区别：valuable / priceless。','系统资产库',92,1),
  ('confusion','translation','valuable / priceless','valuable: 有价值；priceless: 无价','翻译避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: valuable / priceless.','注意这组词的区别：valuable / priceless。','系统资产库',93,1),
  ('confusion','cloze','valuable / priceless','valuable: 有价值；priceless: 无价','完形辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: valuable / priceless.','注意这组词的区别：valuable / priceless。','系统资产库',94,1),
  ('confusion','daily','valuable / priceless','valuable: 有价值；priceless: 无价','基础高频','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: valuable / priceless.','注意这组词的区别：valuable / priceless。','系统资产库',95,1),
  ('confusion','reading','sensible / sensitive','sensible: 理智的；sensitive: 敏感的','阅读辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: sensible / sensitive.','注意这组词的区别：sensible / sensitive。','系统资产库',96,1),
  ('confusion','writing','sensible / sensitive','sensible: 理智的；sensitive: 敏感的','写作避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: sensible / sensitive.','注意这组词的区别：sensible / sensitive。','系统资产库',97,1),
  ('confusion','translation','sensible / sensitive','sensible: 理智的；sensitive: 敏感的','翻译避坑','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: sensible / sensitive.','注意这组词的区别：sensible / sensitive。','系统资产库',98,1),
  ('confusion','cloze','sensible / sensitive','sensible: 理智的；sensitive: 敏感的','完形辨析','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: sensible / sensitive.','注意这组词的区别：sensible / sensitive。','系统资产库',99,1),
  ('confusion','daily','sensible / sensitive','sensible: 理智的；sensitive: 敏感的','基础高频','先看词性、搭配和语境，不要只靠中文近义判断。','Pay attention to the difference: sensible / sensitive.','注意这组词的区别：sensible / sensitive。','系统资产库',100,1);
